version: "2"
volumes:
  data_volume:
  config_volume:
    driver: local
    driver_opts:
      type: none
      device: ./config
      o: bind
  downloads_volume: 
    driver: local
    driver_opts:
      type: none
      device: ./Downloads
      o: bind
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: ./Movies/NuTV
      o: bind
services:
  nutv:
    container_name: nutv
    image: greebowarrior/nutv
    restart: unless-stopped
    ports:
      - 3001:3001
    depends_on:
      - mongo
    links:
      - minidlna
      - mongo
      - transmission
    volumes:
      - downloads_volume:/downloads
      - media_volume:/media
    environment:
      - DB_HOST=mongo
      - MEDIA_ROOT=/media
      - TRANSMISSION_HOST=transmission
      - SECRET_KEY="Correct-Horse-Battery-Staple"
  minidlna:
    container_name: minidlna
    image: vladgh/minidlna
    restart: always
    ports:
      - 8200:8200
    volumes:
      - media_volume:/media
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_FRIENDLY_NAME=NuTV
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017
    volumes:
      - data_volume:/data/db
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: always
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - config_volume:/config
      - downloads_volume:/downloads