version: "2"
volumes:
  data-volume:
  config-volume:
services:
  nutv:
    container_name: nutv
    image: greebowarrior/nutv
    restart: unless-stopped
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    links:
      - minidlna
      - mongo
      - transmission
    volumes:
      - ~/Downloads:/downloads
      - ~/Videos:/videos
    environment:
      - MEDIA_ROOT=/videos
      - DB_HOST=mongo
  minidlna:
    container_name: minidlna
    image: vladgh/minidlna
    ports:
      - "8200:8200"
    volumes:
      - ~/Videos:/media
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_FRIENDLY_NAME=NuTV
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: always
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - config-volume:/config
      - ~/Downloads:/downloads
      - ~/Downloads/watch:/watch